### ISSUE TITLE
感谢 很有帮助

### ISSUE THREAD

**Issue by qq8549149** [SadPencil/Ra2CsfToolsGUI#1]
你好，我来自中国，已经安装使用了，很满意导出的ini文件。

我想批量新增新的字段，可以开发一个吗，谢谢！

如果说

name:xxxx xxxxx
name:xxxx xxxxx
name:xxxx xxxxx
name:xxxx xxxxx
name:xxxx xxxxx

通过一个按钮加到旧的csf文件里

**Comment by SadPencil** [comment]
直接在 ini 文件中粘贴新增的字段不行吗？“批量”指字段批量还是文件批量？

**Comment by SadPencil** [comment]
Close due to inactivity
