### ISSUE TITLE
请问会提供命令行运行方式以集成到CI吗？

### ISSUE THREAD

**Issue by iamapig120** [SadPencil/Ra2CsfToolsGUI#2]
RT

**Comment by SadPencil** [comment]
你可以基于本项目的 Ra2CsfFile 库自己实现一个命令行版，只需要约二十行就可以搞定，参考 https://github.com/SadPencil/Ra2CsfFile/blob/main/ExampleApp/Program.cs

**Comment by iamapig120** [comment]
> 你可以基于本项目的 Ra2CsfFile 库自己实现一个命令行版，只需要约二十行就可以搞定，参考 https://github.com/SadPencil/Ra2CsfFile/blob/main/ExampleApp/Program.cs

感谢，已经看到了，请问该项目会支持以 Windows-1252 方式保存吗？

**Comment by SadPencil** [comment]
> 感谢，已经看到了，请问该项目会支持以 Windows-1252 方式保存吗？

参见 https://github.com/SadPencil/Ra2CsfFile/blob/main/SadPencil.Ra2CsfFile/CsfFileOptions.cs

指定 `CsfFile.Options.Encoding1252WriteWorkaround` 即可

**Comment by iamapig120** [comment]
好的，非常感谢，我试试
